#!/bin/bash
#
# set-hostname-esxcloud        
#
# chkconfig: 
# description:  set a hostname based on dhcp name, required  because eureka expects a unique hostname.
### BEGIN INIT INFO
# Provides:         set-hostname-esxcloud 
# Required-Start:   
# Required-Stop: 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# Source function library.
#Centos
#. /etc/init.d/functions
#Ubuntu
. /lib/lsb/init-functions




RETVAL=$?
HOSTNAME_FILE=/etc/hostname
HOSTS_FILE=/etc/hosts


case "$1" in
 start)
	#Get ip addr using ifconfig
	IP_ADDR=`ifconfig|grep 'inet addr'|grep Bcast|cut -d ':' -f2|cut -d ' ' -f1`
	hostname=$(host $IP_ADDR | cut -d ' ' -f 5 | sed -e 's/\.$//')
	echo $hostname > $HOSTNAME_FILE
	last=`tail -n -1 $HOSTS_FILE`
	if [[ "$last" =~ ^127.* ]]
	then
		sed -i '$ d' $HOSTS_FILE
	fi
	echo '127.0.0.1 '$hostname>>$HOSTS_FILE
	hostname $hostname
	;;
 *)
 	echo $"Usage: $0 {start}"
	exit 1
	;;
esac

exit $RETVAL
